# netlify configuration
# See following link for more information
# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts

[build]
base = "main"
publish = "main/public"
command = "npm run build"
